// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGapXn5CGjs62WFnzCCHXcBblaVO4F-F8',
    appId: '1:123136436815:android:bd3e1fd5048b9011f9983a',
    messagingSenderId: '123136436815',
    projectId: 'my-arabic-learn',
    storageBucket: 'my-arabic-learn.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1ZITi72r_Pn4lLhObD5QRcoSfYZjc04s',
    appId: '1:123136436815:ios:52f396ec0783130ff9983a',
    messagingSenderId: '123136436815',
    projectId: 'my-arabic-learn',
    storageBucket: 'my-arabic-learn.firebasestorage.app',
    androidClientId:
        '123136436815-h3858hqhaoonvkgvegjug8d5coqk9p1i.apps.googleusercontent.com',
    iosClientId:
        '123136436815-l73brhaunb7pssee08640uhfnl09oh20.apps.googleusercontent.com',
    iosBundleId: 'com.arabcha.arabcha',
  );
}
